FROM maven:3.6-jdk-8 as emf-build

RUN git clone -b R2_17_0 git://git.eclipse.org/gitroot/emf/org.eclipse.emf.git
RUN git clone -b R2_17_0 git://git.eclipse.org/gitroot/xsd/org.eclipse.xsd.git
WORKDIR org.eclipse.emf
RUN mvn install

FROM maven:3.6-jdk-8 as build

COPY --from=emf-build /root/.m2/ /root/.m2/
COPY org.opentestmodeling.vstep.ngt.sketch.parent/ apps/

WORKDIR apps
RUN mvn clean install -DskipTests

FROM jetty:9.4.18-jre8

WORKDIR $JETTY_BASE

COPY --from=build /apps/org.opentestmodeling.vstep.ngt.sketch.web/target/org.opentestmodeling.vstep.ngt.sketch.web-1.0.0-SNAPSHOT.war webapps/ROOT.war
